---
title: "hexSticker"
date: "<h4>Updated: <i>`r format( Sys.Date(), '%b-%d-%Y')`</i></h4>"
output:
  BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{hexSticker}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, echo=FALSE, include=TRUE}
pkg <- read.dcf(here::here("DESCRIPTION"), fields = "Package")[1]
description <- read.dcf(here::here("DESCRIPTION"), fields = "Description")[1]

# If you're using R<4.1.1, need this version of rvcheck
# devtools::install_version('rvcheck',version='0.1.8') 
library(hexSticker)
library(dplyr)
library(ggplot2)
library(ggimage)
# library(ggpattern)# remotes::install_github("coolbutuseless/ggpattern")
```

You can make awesome hex stickers for your R packages using:

- [hexSticker](https://github.com/GuangchuangYu/hexSticker)  
- [ggimage](https://github.com/GuangchuangYu/ggimage) 
lets you render images as data points.  
- [ggpattern](https://coolbutuseless.github.io/package/ggpattern/)
lets you fill objects with patterns or images.
- [magick](https://cran.r-project.org/web/packages/magick/vignettes/intro.html) 
modify PNGs.

# `r pkg`

## File path

Create file path to save hex sticker to.

```{r}
filename <- here::here("inst/hex/hex.png")
dir.create(dirname(filename), showWarnings = FALSE, recursive = TRUE)
```

## Subplot

### Network

```{r}
dat <- ThreeWayTest::data_matrix_final
nm <- ThreeWayTest::networkmap(dat = dat)
```

```{r}
x <- nm$plot$data$x
y <- nm$plot$data$y
m=1
tri <- data.frame(x = c(min(x)-m, max(x)/2, max(x)+m),
                  y = c(max(y)+m, min(y)-m, max(y)+m)
                  )
theme_empty <- function(){
    ggplot2::theme_void() +
      ggplot2::theme(legend.position = "none", 
                   panel.background = ggplot2::element_rect(fill = "transparent", colour = "transparent"), 
                   plot.background = ggplot2::element_rect(fill = "transparent",colour = "transparent"))
}
p1 <-ggplot2::ggplot(data = tri, ggplot2::aes(x=x, y=y))+ 
    ggplot2::geom_polygon() +
    theme_empty()
p2 <- nm$plot + theme_empty()
    # ggplot2::scale_x_discrete(expand = ggplot2::expansion(mult = .8)) +
    # ggplot2::scale_y_discrete(expand = ggplot2::expansion(mult = .8))
f <- .9
p1 + patchwork::inset_element(p2, 
                              top = 1*f, 
                              right = 1*f, 
                              bottom = 0+(1-1*f), 
                              left=0+(1-1*f), 
                              align_to = "panel") 
```


### aRtsy triangle

```{r}
set.seed(2024)
colors <- ggplot2::alpha(pals::brewer.pastel2(n = 5),.75)
ga <- aRtsy::canvas_ribbons(colors = colors[1:3],
                            background = "transparent") #+ 
    # ggplot2::scale_y_reverse()
```



## hexSticker 

```{r}    
s_size = 1.95
stick <- hexSticker::sticker( 
  subplot = ga,
  #### Package name ####
  package = pkg, p_size=15, p_y = 1.54,
  #### Subplot #####
  s_x=1*.99, s_y=1,  s_height = s_size, s_width = s_size,
  #### Fill & border ####
  h_fill = colors[4], h_color = colors[5],
  #### Spotlight ####
  spotlight = TRUE, l_alpha = .3, l_width = 10,
  #### File output ####
  filename = filename, dpi = 300)
print(stick)
```

# Session Info 

<details> 

```{r Session Info}
utils::sessionInfo()
```

</details>  
