#' approximate_distribution_coefficient_estimate_T3
#' 
#' This function estimate the coeffcient of T3 with null distribution 
#' generated by  generate_null_distribution_T3.
#' Please see Setp 2 in our manuscript for more information.
#' @param null_distribution_matrix Generated by generate_null_distribution_T3
#' @returns Coefficient matrix of alpha, beta and d.
#' @export
#' @examples 
#' null_distribution<-ThreeWayTest::generate_null_distribution_T3(m=6,n=1000,
#' cov_mat=diag(nrow = 6, ncol = 6), cutoff_value=c(0.2,0.4,0.6,0.8,1))
#' coefficient_matrix <- 
#'     ThreeWayTest::approximate_distribution_coefficient_estimate_T3(
#'     null_distribution_matrix = null_distribution)
approximate_distribution_coefficient_estimate_T3<-
    function(null_distribution_matrix){
        coefficient_matrix<-matrix(0,nrow = 3,ncol = ncol(null_distribution_matrix))
        for (i in 1:ncol(null_distribution_matrix)) {
            coefficient<-coefficient_estimate(null_distribution_matrix[,i])
            coefficient_matrix[1,i]<-coefficient$alpha
            coefficient_matrix[2,i]<-coefficient$beta
            coefficient_matrix[3,i]<-coefficient$d
        }
        return(coefficient_matrix)
    }