#' coefficient_estimate
#' 
#' This function estimate the coeffcient of T3 with null distribution 
#' generated by generate_null_distribution_T3.
#' Please see Setp 2 in our manuscript for more information.
#' @param null_distribution Generated by generate_null_distribution_T3
#' @returns List of coefficient of alpha, beta and d.
#' @export
#' @examples
#' null_distribution<-ThreeWayTest::generate_null_distribution_T3(m=6,n=1000,
#' cov_mat=diag(nrow = 6, ncol = 6), cutoff_value=c(0.2,0.4,0.6,0.8,1))
#' ThreeWayTest::coefficient_estimate(null_distribution[,1])
coefficient_estimate<-function(null_distribution){
    n<-length(null_distribution)
    K1<-(1/n)*sum(null_distribution)
    K2<-(1/n)*sum((null_distribution-K1)^2)
    K3<-(1/n)*sum((null_distribution-K1)^3)
    K4<-(1/n)*sum((null_distribution-K1)^4)-3*(K2^2)
    alpha<-K3/(4*K2)
    beta<-K1-2*(K2^2)/K3
    d<-8*(K2^3)/(K3^2)
    return(list(alpha=alpha,
                beta=beta,
                d=d))
}